name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to trigger the workflow'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
