name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to trigger the workflow'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Create a mod file #It defines the module and its dependencies
      run: go mod init hello  #Here hello is the mod name. Ex. hello.mod

    - name: Build
      run: go build -v ./...  #./... pattern indicates that Go should build all packages in the current directory and its subdirectories.

    - name: Run
      run: ./hello            #After build, If you run your application in linux or mac try .mod_name else if you use windows use mod_name.exe
